account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('user-login', views.user_login, name='user_login'),
    path('user-reg', views.user_reg, name='user_reg'),
    path('logout-user', views.logout_user, name="logout_user"),
    path('admin-login', views.admin_login, name='admin-login'),
    path('reg/2/5/0/admin', views.admin_reg, name='admin-reg'),
    path('logout-admin', views.admin_logout, name='admin-logout')
    
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('apply', views.user_apply, name='user_apply'),
    path('permit-apply', views.permit_apply, name='permit-apply'),
    path('group-apply', views.group_apply, name='group-apply'),
    path('my-loans', views.my_loans, name='my-loans'),
    path('my-payments', views.my_payments, name='my-payments'),
    path('support', views.support, name='support'),
    path('about', views.about, name='about'),
    path('sms', views.sms, name="sms")
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('loan/', include('loan.urls')),
    path('account/', include('account.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

loan/urls.py
from os import name
from django.urls import path, re_path
from . import views

app_name = 'loan'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('manage-loans/', views.manage_loans, name='manage-loans'),
    path('manage-group-loans/', views.manage_group_loans, name='manage_group_loans'),
    path('loan-approve/', views.loan_approve, name='loan-approve' ),
    path('group-loan-approve/', views.group_loan_approve, name='group-loan-approve'),
    path('group-loan-remove/', views.group_loan_remove, name='group-loan-remove'),
    path('loan-remove/', views.loan_remove, name='loan-remove'),
    path('loan-complete/', views.loan_complete, name='loan-complete'),
    re_path(r'^pay-details/(?P<ref>(.*))/$', views.pay_details, name='pay-details'),
    re_path(r'^fee-details/(?P<loan_id>(.*))/$', views.fee_details, name='fee-details'),
    path('group-loan-complete', views.group_loan_complete, name='group-loan-complete'),
    path('add-payment', views.add_payment, name='add-payment'),
    path('manual-add-payment', views.manual_add_payment, name='manual-add-payment'),
    path('group-add-payment', views.group_add_payment, name='group-add-payment'),
    path('payment-record', views.payment_record, name='payment-record'),
    path('group-payment-record', views.group_payment_record, name='group-payment-record'),
    re_path(r'^(?P<loan_id>[0-9]+)/$', views.loan_details, name='loan-details'),
    path('all-clients', views.all_clients, name='all-clients'),
    path('staff', views.staff, name='staff'),
    path('complaints', views.complaints, name='complaints'),
    re_path(r'^view_reply/(?P<error_id>[0-9]+)/$', views.reply, name='reply'),
    re_path(r'^done/(?P<quest_id>[0-9]+)/$', views.done, name='done'),
    re_path(r'^group/(?P<group_l_id>[0-9]+)/$', views.group_details, name='group-details'),
    path('send-report', views.send_report, name='send-report'),

    # permit section

    path('permit-dashboard', views.permit_dashboard, name='permit-dashboard'),
    path('permit-add-payment', views.permit_add_payment, name='permit-add-payment'),
    path('permit-payment-details', views.permit_payment_details, name='permit-payment-details'),
    re_path(r'^permit-pay-details/(?P<ref>(.*))/$', views.permit_pay_details, name='permit-pay-details'),
    path('permit-clients', views.permit_clients, name='permit-clients'),
    path('files-upload', views.files_upload, name='files-upload'),
    path('search-client', views.search_client, name='search-client'),
    path('search-client-trigger', views.search_client_trigger, name='search-client-trigger'),
    re_path(r'^file-details/(?P<permitId>[0-9]+)/$', views.file_details, name='file-details'),
    path('permit-logs', views.permit_logs, name='permit-logs'),
    path('loan-logs', views.loan_logs, name='loan-logs'),
    re_path(r'^edit_permit/(?P<permitID>[0-9]+)/$', views.permit_edit_details, name='edit-permit'),
    path('client-csv', views.client_csv, name='client-csv'),
    path('post-permit-edit', views.post_permit_edit, name='post-permit-edit'),

    # boda bodas
    path('add-boda', views.add_boda, name="add-boda"),
    path('boda-dashboard', views.boda_dashboard, name="boda-dashboard"),
    path('search-client-boda', views.search_client_boda, name='search-client-boda'),
    path('manual-add-boda-payment', views.manual_add_boda_pay, name="add-boda-pay"),
    path('search-boda', views.search_boda_trigger, name="search-boda"),
    path('weekly-logs', views.weekly_logs, name="weekly-logs"),
    path('full-boda-logs', views.full_week_logs, name="full-week-logs"),
    re_path(r'^boda-details/(?P<bodaId>[0-9]+)/$', views.boda_details, name='boda-detail'),
    path('sms-status', views.sms_statuses, name="sms-statuses"),
    re_path(r'^edit-boda/(?P<bodaId>[0-9]+)/$', views.edit_boda, name="edit-boda"),
    re_path(r'^change-boda-status/(?P<boda_id>[0-9]+)/$', views.change_boda_status, name="change-boda-status"),
    path('archived-boda', views.archived_boda, name="archived-boda"),
    path('cashflows', views.cashflows, name="cashflows"),
    path('add-cashflow', views.addCashFlow, name="add-cashflow"),
    path('advanced-information', views.advancedBodaInformation, name="advanced-information"),
    path('add-information', views.addBodainformation, name="add-information"),
    re_path(r'^edit-boda-information/(?P<NumberPlate>(.*))/$', views.editBodaInformation, name="edit-boda-information"),
    re_path(r'^resend-boda-sms/(?P<transID>(.*))/$', views.resend_boda_sms, name="resend-boda-sms")
]

account/models.py
from django.db import models

account/views.py
from django.shortcuts import redirect, render
from django.contrib.auth.models import User, auth
from django.contrib import messages
# Create your views here.

# user login
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        # form authentication
        if username == '':
            return redirect('user-login')
        elif password == '':
            return redirect('user-login')
        else:
            # user authenticate
            user = auth.authenticate(
                username = username,
                password = password
            )

            if user is None:
                messages.error(request, 'invalid user credentials')
                return redirect('account:user_login')
            else:
                auth.login(request, user)
                return redirect('home:index')

    else:
        return render(request, 'log_user.html')

# user registering
def user_reg(request):
    if request.method == 'POST':
        data = request.POST
        fname = data['fname']
        lname = data['lname']
        username = data['username']
        email = data['email']
        password1 = data['password']
        password2 = data['confirm_password']

        # confirm password
        if fname == '':
            messages.error(request, 'First name cannot be empty')
            return redirect('account:user_reg')
        elif lname == '':
            messages.error(request, "Last name cannot be emoty")
            return redirect('account:user_reg')
        elif username == '':
            messages.error(request, 'Username cannot be empty')
            return redirect('account:user_reg')
        elif email == '':
            messages.error(request, 'email field cannot be empty')
            return redirect('account:user_reg')
        elif password1 != password2:
            messages.error(request, 'passwords do not match')
            return redirect('account:user_reg')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exist')
            return redirect('account:user_reg')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'Already registered an account with this email')
            return redirect('account:user_reg')
        else:

            user = User.objects.create_user(
                username=username,
                password=password1,
                email=email,
                first_name=fname,
                last_name=lname,
                is_staff=True,
                is_active=True,
            )

            # authenticate and login the user
            auth.login(request, user)
            return redirect('home:index')
    else:
        return render(request, 'reg_user.html')

# logout user
def logout_user(request):
    auth.logout(request)
    return redirect('account:user_login')

# user admin login
def admin_login(request):
    if request.method == 'POST':
        data = request.POST.get
        username = data('username')
        password = data('password')

        # form authentication
        if username == '':
            return redirect('admin-login')
        elif password == '':
            return redirect('admin-login')
        else:
            # user authenticate
            user = auth.authenticate(
                username = username,
                password = password
            )

            if user is None:
                messages.error(request, 'invalid user credentials')
                return redirect('account:admin-login')
            else:
                auth.login(request, user)
                return redirect('loan:dashboard')

    else:
        return render(request, 'log_admin.html')

def admin_reg(request):
    if request.method == 'POST':
        data = request.POST
        fname = data['fname']
        lname = data['lname']
        username = data['username']
        email = data['email']
        password1 = data['password']
        password2 = data['confirm_password']

        # confirm password
        if fname == '':
            messages.error(request, 'First name cannot be empty')
            return redirect('account:user_reg')
        elif lname == '':
            messages.error(request, "Last name cannot be emoty")
            return redirect('account:user_reg')
        elif username == '':
            messages.error(request, 'Username cannot be empty')
            return redirect('account:user_reg')
        elif email == '':
            messages.error(request, 'email field cannot be empty')
            return redirect('account:user_reg')
        elif password1 != password2:
            messages.error(request, 'passwords do not match')
            return redirect('account:user_reg')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'Username already exist')
            return redirect('account:user_reg')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'Already registered an account with this email')
            return redirect('account:user_reg')
        else:

            user = User.objects.create_user(
                username=username,
                password=password1,
                email=email,
                first_name=fname,
                last_name=lname,
                is_staff=True,
                is_active=True,
                is_superuser=True,
            )

            # authenticate and login the user
            auth.login(request, user)
            return redirect('loan:dashboard')
    else:
        return render(request, 'admin_reg.html')
def admin_logout(request):
    auth.logout(request)
    return redirect('account:admin-login')

account/templates/edit_boda.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
        <section class="admin-content">
                <div class=" bg-dark m-b-30 bg-stars">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-8 m-auto text-white p-t-40 p-b-90">
                                {% for message in messages %}
                                    <div class="alert alert-border-info  alert-dismissible fade show" role="alert">
                                        <div class="d-flex">
                                            <div class="icon">
                                                <i class="icon mdi mdi-alert-octagram"></i>
                                            </div>
                                            <div class="content text-dark">
                                                {{message}}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                                <h1><span class="js-greeting"></span>, {{ user }} </h1>
                                <p class="opacity-75">
                                    EDIT BODA <br>
                                </p>

                            </div>
                            <div class="col-md-4 m-auto text-white p-t-40 p-b-90">
                                
                            </div>
                        </div>
                    </div>

                </div>
                <div class="container pull-up">

                    <!-- // Normal content -->
                   
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="card m-b-30">
                                    <div class="card-header">
                                        <h5 class="m-b-0">
                                            Edit Boda Details Page
                                        </h5>
                                        <p class="m-b-0 text-muted">
                                            Standard form
                                        </p>
                                    </div>
                                    <div class="card-body ">
                                        <form action="{% url 'loan:edit-boda' boda.boda_id %}" method="post">
                                            {% csrf_token %}
                                            <div class="form-row">
                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">Number Plate</label>
                                                    <input type="text" class="form-control numberPlate" name="numberPlate" value="{{boda.boda_numberPlate}}">
                                                    <div class="text-muted" id="manual_client_res"></div>
                                                </div>

                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">client First Name</label>
                                                    <input type="text" class="form-control" name="firstName" value="{{boda.boda_guy_firstName}}">
                                                </div>

                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">client Last Name</label>
                                                    <input type="text" class="form-control" name="lastName" value="{{boda.boda_guy_lastName}}">
                                                </div>

                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">client Final Amount</label>
                                                    <input type="text" class="form-control" name="fullAmount" value="{{boda.final_amount}}">
                                                </div>

                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">client Deposits</label>
                                                    <input type="text" class="form-control" name="deposits" value="{{boda.deposits}}">
                                                </div>

                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">client Balance</label>
                                                    <input type="text" class="form-control" name="balance" value="{{boda.balance}}">
                                                </div>

                                                <div class="form-group col-md-12">
                                                    <label for="inputPassword4">Boda Date of application *</label>
                                                    <input type="text" class="form-control date_of_application" name="date_of_application" value="{{boda.date_of_application}}">
                                                    <small class="text-muted">put the date of application</small>
                                                </div>
                                            </div>
                                            <div class="form-group">
                                                <button class="btn btn-primary">Submit</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        
                </div>

            </section>

            <script>
                
                document.addEventListener("DOMContentLoaded", function () {
                    flatpickr(".date_of_application", {
                        enableTime: true,
                        dateFormat: "M. j, Y, h:i K",
                    });
                });
            </script>
    
    {% endblock %}

account/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Money access uganda</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.theme.default.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive1.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/about.css' %}">
</head>

<body>
    <div class="wrapper">
        <header class="header">
            <section class="header-bottom">
                <div class="container">
                    <div class="row">
                        <div class="col-md-5 col-sm-12 col-xs-12">
                            <a href="#">
                                <div class="main-logo">
                                    <img src="{% static 'assets/img/logo.svg' %}" alt="">
                                   <h2><a href="/">Money Access Uganda</a></h2>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-7 col-sm-12 col-xs-12">
                            <div class="menu">
                                <ul class="nav navbar-nav">
                                    <li class="active"><a href="/">Home</a></li>
                                    <li><a href="{% url 'home:my-loans' %}">My Loans</a></li>
                                    <li><a href="{% url 'home:my-payments' %}">My Payments</a></li>
                                    <li><a href="{% url 'home:about' %}">About Us</a></li>
                                    <li><a href="{% url 'home:support' %}">Help/Support</a></li>
                                    <li><a href='{% url 'account:logout_user' %}'>Logout</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </header>
        <section class="carosal-area" style="background-image: url('{% static 'assets/img/money1.jpeg' %}')">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="client owl-carousel owl-theme">
                            <div class="item">
                                <div class="text">
                                    <h3>If you would know the value of money, go and try to borrow some.</h3>
                                    <h5 class="white-button"><a href="{% url 'home:user_apply' %}">Apply Loan As Individual</a></h5>
                                    <h5 class="white-button"><a href="{% url 'home:group-apply' %}">Apply Loan As Group</a></h5>
                                    <h5 class="white-button"><a href="{% url 'home:permit-apply' %}">Apply Loan For Permit</a></h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
    <script src="{% static 'assets/js/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'assets/js/animationCounter.js' %}"></script>
    <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'assets/js/active.js' %}"></script>

</body>
<footer>
    <div class="footer-content">
        <h3>Money Access Uganda</h3>
        <p>we help provide loans to needful people around for a given period of time.</p>
        
    </div>
    <div class="footer-bottom">
        <p>copyright &copy;2021 <a href="tel: +256 775 555 464">AndySolutions</a>  </p>
        
    </div>
    
</footer>

</html>

account/templates/permit_payment_details.html
{% extends 'base.html' %}
{% load static %}

    {% block content %}
    <section class="admin-content">
        <div class=" bg-dark m-b-30 bg-stars">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 m-auto text-white p-t-40 p-b-90">
                        {% for message in messages %}
                                    <div class="alert alert-border-info  alert-dismissible fade show" role="alert">
                                        <div class="d-flex">
                                            <div class="icon">
                                                <i class="icon mdi mdi-alert-octagram"></i>
                                            </div>
                                            <div class="content text-dark">
                                                {{message}}
                                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                        </div>
                                    </div>
                            {% endfor %}
                        <h1>Permit Daily Payments View</h1>
                        <p class="opacity-75">
                            Client's daily payments.
                        </p>

                    </div>
                    <div class="col-md-4 m-auto text-white p-t-40 p-b-90">
                        
                    </div>
                </div>
            </div>

        </div>
        <div class="container pull-up">
            <div class="row">

                <!-- Content goes here -->
                <div class="col-lg-8">
                    <nav class="nav nav-pills nav-justified m-b-80">
                    <a class="nav-item nav-link text-white active" href="{% url 'loan:permit-dashboard' %}">Money Access Uganda</a>
                    </nav>
                </div>
                <div class="col-lg-12">
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                        
                            <div class="col-md-12 m-b-30">
                                <h5>Payments</h5>
                                <div class="table-responsive">
                                    <table class="table align-td-middle table-card table-striped">
                                        <thead>
                                        <tr>
                                            <th>PERMIT ID</th>
                                            <th>PAYMENT FEE</th>
                                            <th>Transaction ID</th>
                                            <th>Status</th>
                                            <th>DATE</th>
                                            <th>APPROVED BY</th>
                                            <th>Check</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% if request.user.username == "george@accessm.com" or request.user.username == "BRENDAR" or request.user.username == "ADMIN" %}
                                            {% for payment in admin_payments %}
                                                    <tr>
                                                        <td>
                                                            {{payment.permit_id}}
                                                        </td>
                                                        <td>Ugx {{payment.payment_fee}}</td>
                                                        <td>{{payment.transaction_id}}</td>
                                                        <td>{{payment.status}}</td>
                                                        <td>{{payment.date}}</td>
                                                        <td>{{payment.admin}}</td>
                                                        {% if payment.transaction_id == "manual pay" %}
                                                        
                                                        <td>cash at hand</td>
                                                        {% elif payment.transaction_id == "NOT PAID" %}
                                                        <td>failed</td>
                                                        {% else %}
                                                        <td>
                                                            <a class='btn hvr-hover' href="{% url 'loan:permit-pay-details' payment.reference %}">View</a>
                                                        
                                                        </td>
                                                        {% endif %}
                                                    </tr>
                                            {% endfor %}

                                        {% elif request.user.username != "george@accessm.com" %}
                                        {% for payment in payments %}
                                        <tr>
                                            <td>
                                                {{payment.permit_id}}
                                            </td>
                                            <td>Ugx {{payment.payment_fee}}</td>
                                            <td>{{payment.transaction_id}}</td>
                                            <td>{{payment.status}}</td>
                                            <td>{{payment.date}}</td>
                                            <td>{{payment.admin}}</td>
                                            {% if payment.transaction_id == "manual pay" %}
                                                        
                                                <td>cash at hand</td>
                                            {% elif payment.transaction_id == "NOT PAID" %}
                                                <td>failed</td>
                                            {% else %}
                                                <td>
                                                    <a class='btn hvr-hover' href="{% url 'loan:permit-pay-details' payment.reference %}">View</a>
                                                
                                                </td>
                                            {% endif %}
                                        </tr>
                                        {% endfor %}
                                        {% else %}
                                                <tr>
                                                    <td><h6>No record in DB</h6></td>
                                                </tr>
                                        {% endif %}
                                        </tbody>
                                    </table>

                                </div>
                            </div>

                        </div>
                                        
                    </div>
        </div>

    </section>
    {% endblock %}